#! /bin/sh 
#
# Autostart
#
pgrep -x sxhkd > /dev/null || sxhkd -m -1 &
# Set display from arandr saved script
sh ~/.screenlayout/dualmonitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill --randomize $HOME/Rice/Wallpapers/TokyoNight-* &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom &
# Network Applet
nm-applet --indicator &

bspc monitor VGA1 -s HDMI1
bspc monitor HDMI1 -d I II III IV V
bspc monitor VGA1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#787c99"
bspc config normal_border_color         "#1a1b26"
bspc config active_border_color         "#1a1b26"

# Cursor
xsetroot -cursor_name left_ptr &
setxkbmap -option shift:both_capslock &
xmodmap -e "clear Lock" &
setxkbmap -option caps:ctrl_modifier &
xcape -e Caps_Lock=Escape -t 200
